/**
 * @fileoverview a11y-audit.a11y.e2e.js
 * Automated accessibility audit — all 46 pseudo-kit components.
 * Story: S8-04
 *
 * Uses @axe-core/playwright to scan the a11y harness page.
 * Run: npx playwright test --config playwright.a11y.config.js
 *
 * Severity levels tested: critical, serious (must be 0)
 * Moderate + minor are collected and logged but not blocking.
 */

import { test, expect } from '@playwright/test';
import { AxeBuilder } from '@axe-core/playwright';
import { writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const ARTIFACTS_DIR = join(ROOT, 'bmad/artifacts');

// ── Helpers ──────────────────────────────────────────────────────────────────

function severityEmoji(impact) {
  return { critical: '🔴', serious: '🟠', moderate: '🟡', minor: '⚪' }[impact] ?? '❓';
}

function formatViolation(v) {
  const nodes = v.nodes.map(n => `  - \`${n.html.slice(0, 120)}\``).join('\n');
  return `### ${severityEmoji(v.impact)} [${v.impact?.toUpperCase()}] ${v.id}\n` +
    `**Rule:** ${v.description}\n` +
    `**Help:** ${v.helpUrl}\n` +
    `**Affected nodes (${v.nodes.length}):**\n${nodes}`;
}

function buildReport(violations, incompletes, date) {
  const critical  = violations.filter(v => v.impact === 'critical');
  const serious   = violations.filter(v => v.impact === 'serious');
  const moderate  = violations.filter(v => v.impact === 'moderate');
  const minor     = violations.filter(v => v.impact === 'minor');

  const lines = [
    `# A11y Audit Report — pseudo-kit (all 46 components)`,
    ``,
    `> **Date:** ${date} | **Tool:** axe-core via @axe-core/playwright | **Browser:** Chromium`,
    ``,
    `---`,
    ``,
    `## Summary`,
    ``,
    `| Severity | Count | Blocking |`,
    `|:---------|:-----:|:--------:|`,
    `| 🔴 Critical | ${critical.length} | Yes |`,
    `| 🟠 Serious  | ${serious.length} | Yes |`,
    `| 🟡 Moderate | ${moderate.length} | No  |`,
    `| ⚪ Minor    | ${minor.length} | No  |`,
    ``,
    `**Incomplete checks (needs review):** ${incompletes.length}`,
    ``,
    `---`,
  ];

  if (critical.length + serious.length === 0) {
    lines.push(``, `## ✅ No Critical or Serious violations found`, ``);
  }

  if (critical.length) {
    lines.push(``, `## 🔴 Critical Violations (must fix — S8-05)`, ``);
    critical.forEach(v => lines.push(formatViolation(v), ``));
  }

  if (serious.length) {
    lines.push(``, `## 🟠 Serious Violations (must fix — S8-05)`, ``);
    serious.forEach(v => lines.push(formatViolation(v), ``));
  }

  if (moderate.length) {
    lines.push(``, `## 🟡 Moderate Violations (backlog)`, ``);
    moderate.forEach(v => lines.push(formatViolation(v), ``));
  }

  if (minor.length) {
    lines.push(``, `## ⚪ Minor Violations (backlog)`, ``);
    minor.forEach(v => lines.push(formatViolation(v), ``));
  }

  if (incompletes.length) {
    lines.push(``, `## ❓ Incomplete (needs manual review)`, ``);
    incompletes.slice(0, 10).forEach(i => {
      lines.push(`- **${i.id}**: ${i.description}`);
    });
    if (incompletes.length > 10) lines.push(`- _…and ${incompletes.length - 10} more_`);
  }

  lines.push(``, `---`, ``, `_Generated by BMAD S8-04 — run \`pnpm test:a11y\` to refresh._`);

  return lines.join('\n');
}

// ── Test Suite ────────────────────────────────────────────────────────────────

test.describe('A11y audit — all 46 pseudo-kit components', () => {

  test('full page scan — 0 critical, 0 serious violations', async ({ page }) => {
    await page.goto('/a11y-audit.html');

    // Wait for all 46 components to resolve
    await page.waitForFunction(
      () => window.__pkA11yReady === true,
      { timeout: 30_000 }
    );

    // Run axe on the full audit root
    const results = await new AxeBuilder({ page })
      .include('#audit-root')
      .withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa', 'best-practice'])
      .analyze();

    const { violations, incomplete } = results;

    // Persist the audit report
    const date = new Date().toISOString().slice(0, 10);
    const reportPath = join(ARTIFACTS_DIR, `a11y-audit-${date}.md`);
    mkdirSync(ARTIFACTS_DIR, { recursive: true });
    writeFileSync(reportPath, buildReport(violations, incomplete, date), 'utf8');
    console.log(`\n📄 A11y report saved → ${reportPath}`);

    // Log summary
    const critical = violations.filter(v => v.impact === 'critical');
    const serious  = violations.filter(v => v.impact === 'serious');
    const moderate = violations.filter(v => v.impact === 'moderate');
    const minor    = violations.filter(v => v.impact === 'minor');

    console.log(`\n🔴 Critical: ${critical.length}  🟠 Serious: ${serious.length}  🟡 Moderate: ${moderate.length}  ⚪ Minor: ${minor.length}`);

    if (violations.length > 0) {
      console.log('\nViolations:');
      violations.forEach(v => {
        console.log(`  ${severityEmoji(v.impact)} [${v.impact}] ${v.id}: ${v.description}`);
        v.nodes.forEach(n => console.log(`      → ${n.html.slice(0, 100)}`));
      });
    }

    // S8-04 goal: surface all violations (report written above)
    // S8-05 goal: fix Critical + Serious (assert 0 blocking violations)
    expect(
      critical.length,
      `${critical.length} critical violation(s) found — check bmad/artifacts/a11y-audit-${date}.md`
    ).toBe(0);

    expect(
      serious.length,
      `${serious.length} serious violation(s) found — check bmad/artifacts/a11y-audit-${date}.md`
    ).toBe(0);
  });

  test('atoms layer — no critical or serious violations', async ({ page }) => {
    await page.goto('/a11y-audit.html');
    await page.waitForFunction(() => window.__pkA11yReady === true, { timeout: 30_000 });

    const results = await new AxeBuilder({ page })
      .include('[data-layer="atoms"]')
      .withTags(['wcag2a', 'wcag2aa'])
      .analyze();

    const blocking = results.violations.filter(v =>
      v.impact === 'critical' || v.impact === 'serious'
    );

    if (blocking.length > 0) {
      console.log('\nAtoms — blocking violations:');
      blocking.forEach(v => console.log(`  ${severityEmoji(v.impact)} ${v.id}: ${v.description}`));
    }

    expect(blocking.length, 'Atoms: blocking a11y violations found').toBe(0);
  });

  test('molecules layer — no critical or serious violations', async ({ page }) => {
    await page.goto('/a11y-audit.html');
    await page.waitForFunction(() => window.__pkA11yReady === true, { timeout: 30_000 });

    const results = await new AxeBuilder({ page })
      .include('[data-layer="molecules"]')
      .withTags(['wcag2a', 'wcag2aa'])
      .analyze();

    const blocking = results.violations.filter(v =>
      v.impact === 'critical' || v.impact === 'serious'
    );

    if (blocking.length > 0) {
      console.log('\nMolecules — blocking violations:');
      blocking.forEach(v => console.log(`  ${severityEmoji(v.impact)} ${v.id}: ${v.description}`));
    }

    expect(blocking.length, 'Molecules: blocking a11y violations found').toBe(0);
  });

  test('organisms layer — no critical or serious violations', async ({ page }) => {
    await page.goto('/a11y-audit.html');
    await page.waitForFunction(() => window.__pkA11yReady === true, { timeout: 30_000 });

    const results = await new AxeBuilder({ page })
      .include('[data-layer="organisms"]')
      .withTags(['wcag2a', 'wcag2aa'])
      .analyze();

    const blocking = results.violations.filter(v =>
      v.impact === 'critical' || v.impact === 'serious'
    );

    if (blocking.length > 0) {
      console.log('\nOrganisms — blocking violations:');
      blocking.forEach(v => console.log(`  ${severityEmoji(v.impact)} ${v.id}: ${v.description}`));
    }

    expect(blocking.length, 'Organisms: blocking a11y violations found').toBe(0);
  });

});
